name: CI
on:
  pull_request:
  push:
    branches: main
    
jobs:
  support:
    name: Support
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install xcbeautify
      run: brew install xcbeautify
    - name: Run tests
      run: xcodebuild clean test -workspace Planetary.xcworkspace -scheme Support -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" | xcbeautify
