name: CI
on:
  pull_request:
  push:
    branches: main
    
jobs:
  support:
    name: Support
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -workspace Planetary.xcworkspace -scheme Support -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -workspace Planetary.xcworkspace -scheme Support -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" | tee xcodebuild.log | xcpretty
